version: "3.9"

networks:
  next-app:
    external: true

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - $FPORT:$FPORT
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - next-app


  backend:
    container_name: backend
    build: ./backend
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "yarn && yarn typeorm migration:run -d src/data-source && yarn dev"
    volumes:
      - .:/app
    networks:
      - next-app

  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - $PGPORT:$PGPORT
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - next-app
