import { BalanceCard } from "../../components/common/balance";
import { useContext } from "react";
import { AuthContext } from "../../contexts/AuthContext";
import { GetServerSideProps } from "next";
import { parseCookies } from "nookies";

import Head from "next/head";
import { getAPIClient } from "../../api/axios";
import { GenericCard } from "../../components/common/genericCard";

interface PropData {
  balance: string;
}

export default function Dashboard({ balance }: PropData) {
  const { user, signOut } = useContext(AuthContext);

  return (
    <div className="h-screen bg-white">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full max-w-[850px] mx-auto flex flex-col gap-5 px-5 py-10">
        <div className="flex justify-between items-center border-b animate-menuSlide">
          <h1 className="text-4xl font-bold drop-shadow-md lg:mb-5">
            Olá,
            <span className="inline-block w-full lg:inline lg:ml-1 text-primary mb-2">
              {user?.username}
            </span>
          </h1>
          <button onClick={signOut} className="bg-none border h-fit p-5 rounded-full shadow-md font-bold lg:mb-5">Sair</button>
        </div>
        <div className="grid grid-cols-2 gap-5 animate-buttonSlideUp">
          <BalanceCard balance={balance} />
          <GenericCard title="Histórico" descripton="Visualize suas compras e seus recebimentos" link="/transactions" primary={true} />
          <GenericCard title="Pix" link="/pix" />
          <GenericCard title="Placeholder" link="/dashboard" />
          <GenericCard title="Placeholder" link="/dashboard" />
          <GenericCard title="Placeholder" link="/dashboard" />
        </div>
      </div>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const apiClient = getAPIClient(ctx);
  const { ["next.token"]: token } = parseCookies(ctx);

  if (!token) {
    return {
      redirect: {
        destination: "/iniciar-sessao",
        permanent: false,
      },
    };
  }

  const response = await apiClient.get("account");
  const { balance } = response.data;

  return {
    props: {
      balance,
    },
  };
};
