import Head from "next/head";
import { Form } from "../../components/common/form";

export default function RegisterPage() {
  return (
    <div className="h-screen bg-black text-white">
      <Head>
        <title>Iniciar Sessão</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full max-w-[450px] mx-auto flex flex-col gap-5 justify-center px-5 py-10">
        <div className="flex flex-col animate-menuSlide">
          <h2 className="text-5xl text-white font-bold tracking-tight">
            FAÇA SEU
          </h2>
          <h2 className="text-5xl text-white font-bold tracking-tight">
            LOGIN
          </h2>
          <h2 className="text-5xl text-white font-bold tracking-tight">
            NA NOVA
          </h2>
          <h2 className="text-5xl text-primary font-bold tracking-tight">
            GERAÇÃO.
          </h2>
        </div>
        <div>
          <Form formType="login" />
        </div>
      </div>
    </div>
  );
}
